[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-C", "link-arg=-Tsrc/kernel.ld"]

[target.riscv64gc-unknown-none-elf]
runner = """
  qemu-system-riscv64
  -machine virt
  -bios default
  -nographic
  -serial mon:stdio
  --no-reboot
  -kernel
"""
